services:
  sportswear.api:
    image: ${DOCKER_REGISTRY-}sportswearapi
    build:
      context: .
      dockerfile: Sportswear.Api/Dockerfile
    environment:
      - ConnectionStrings__cs=${CS_CONNECTION}
      - ConnectionStrings__HangfireConnection=${HANGFIRE_CONNECTION}
      - jwtSettings__secret=${JWT_SECRET}
      - jwtSettings__issuer=${JWT_ISSUER}
      - jwtSettings__audience=${JWT_AUDIENCE}
      - emailSettings__FromEmail=${EMAIL_FROM}
      - emailSettings__password=${EMAIL_PASSWORD}
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - images_data:/app/wwwroot/images
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "8080:8080"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1", "-No"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  sqlserver_data:
  images_data: